exclude: 'migrations/.*'
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
  # - repo: https://github.com/psf/black
  #   rev: 23.3.0
  #   hooks:
  #     - id: black
  #       args: [
  #         '--line-length=80',
  #          '--multi-line=3',
  #          '--force-grid-wrap=0',
  #          '--trailing-comma',
  #          '--use-parentheses',
  #          '--ensure-newline-before-comments',
  #       ]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
